# Header
menu:
  首页: /
links:
  rss: /sitemap.xml
  github: github地址
  heart: /自定义路径

# Site Info
signature: 这里是作者描述
since: 建站初始时间，如：2010

# Layout config
avatar: true
animation: true

# Third part comments
# total switch
# 关闭评论，设置为false
# 开启评论，设置为指定评论名： GITHUB-issues Hyper评论-hyper
social_comment: issues
# comment accounts
hyper_id: ''
issues:
  owner: ''
  repo: ''
  client_id: ''
  client_secret: ''

# sponser

sponsor:
  enable: false
  code: ''

footLinks:

# extend head code(script Or style)
customer:
  headCode: ''

# special style
styles:
  gray: false